apiVersion: v1
kind: Secret
metadata:
  name: microshop-secrets
type: Opaque
stringData:
  db.user: "postgres"
  db.password: "postgres"
  jwt.secret: "your-256-bit-secret-key-for-jwt-token-generation-minimum-32-characters"
