apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: taskmanager

resources:
  - ../../base

images:
  - name: taskmanager/server
    newTag: latest
  - name: taskmanager/web
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: server
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: web
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Ingress
      name: taskmanager-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: localhost