export type { IRes } from './api.interface'
export { EResponseStatus } from './api.interface'
export type { IUser, IUserAdmin } from './user.interface'
export type { ICountry } from './country.interface'
export type { ICity } from './city.interface'
export type { ILocation, ILocationType } from './location.interface'
export type { IEvent, IEventAdmin, IEventLocation, TEventStatus } from './event.interface'
