---
apiVersion: v1
kind: Secret
metadata:
  name: server-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://app_user:CHANGE_ME@postgres:5432/app_db?schema=public"
  REDIS_URL: "redis://redis:6379"
  JWT_ACCESS_SECRET: "CHANGE_ME_IN_PRODUCTION_ACCESS_SECRET"
  JWT_REFRESH_SECRET: "CHANGE_ME_IN_PRODUCTION_REFRESH_SECRET"
