spring:
  application:
    name: ${APPLICATION_NAME:server}
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_USER_PASSWORD:1111}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
management:
  server:
    port: ${SERVER_PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:change-me-please}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
